baseURL = "https://better-move.netlify.app/"
languageCode = "en-us"
title = "Youth Chess Training"

[permalinks]
    post = "/:year/:month/:day/:slug/"
	timeless = "/:slug/"

[taxonomies]
	category = "categories"
	tag = "tags"
	
[[menu.main]]
    name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
    name = "About"
	url = "/about"
	weight = 2
[[menu.main]]
    name = "Blog"
	url = "/categories/blog/"
	weight = 3
