baseURL = "https://atomblog.netlify.com/"
languageCode = "en-us"
title = "Ars Atomica"
copyright = "Illion 2017-2019"

[params]
    author = "Illion"
	footer = "&copy; [Illion](https://lichess.org/@/Illion) 2017-2019 | Theme by Marken Foo"

[permalinks]
    post = "/:year/:month/:day/:slug/"
	timeless = "/:slug/"
	
[taxonomies]
	category = "categories"
	series = "series"
	tag = "tags"
	
[[menu.main]]
    name = "Home"
	url = "/"
	weight = 1
[[menu.main]]
    name = "About"
	url = "/about/"
	weight = 2
[[menu.main]]
    name = "Rules of atomic"
	url = "/atomic-rules/"
	weight = 3
[[menu.main]]
    name = "Blog"
	url = "/categories/blog/"
	weight = 4
[[menu.main]]
	name = "Resources"
	url = "/resources/"
	weight = 5
[[menu.main]]
    name = "Links"
	url = "/links/"
	weight = 6
	
